# Server Configuration
server.port=8080

# Database Connection - Uses Cloud URL if available, otherwise uses Localhost
spring.datasource.url=${Render_DB_URL:jdbc:postgresql://localhost:5432/student_marketplace}
spring.datasource.username=${Render_DB_Username:postgres}
spring.datasource.password=${Render_DB_Password:1206}

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
api.cors.allowed-origins=*00